Address:
    type: entity
    table: address
    indexes:
        fk_person_id:
            columns:
                - FKPersonId
        fk_country_id:
            columns:
                - FKCountryId
        fk_city_id:
            columns:
                - FKCityId
        fk_region_id:
            columns:
                - FKRegionId
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        street:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Street
        city:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: City
        postcode:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: PostCode
    manyToOne:
        fkcityid:
            targetEntity: GdCities
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                FKCityId:
                    referencedColumnName: city_id
            orphanRemoval: false
        fkcountryid:
            targetEntity: GdCountries
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                FKCountryId:
                    referencedColumnName: id
            orphanRemoval: false
        fkpersonid:
            targetEntity: Person
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                FKPersonId:
                    referencedColumnName: id
            orphanRemoval: false
        fkregionid:
            targetEntity: GdRegions
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                FKRegionId:
                    referencedColumnName: region_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
