GdConfigurations:
    type: entity
    table: gd_configurations
    id:
        configurationId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: configuration_id
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
        dateCreated:
            type: datetime
            nullable: false
            comment: ''
            column: date_created
        lastUpdated:
            type: datetime
            nullable: false
            comment: ''
            column: last_updated
        accountId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: account_id
        configurationName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: configuration_name
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        numRowsGenerated:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: num_rows_generated
    lifecycleCallbacks: {  }
