GdFirstNames:
    type: entity
    table: gd_first_names
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: first_name
        gender:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: male
    lifecycleCallbacks: {  }
