GdSettings:
    type: entity
    table: gd_settings
    uniqueConstraints:
        setting_name:
            columns:
                - setting_name
    id:
        settingName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            id: true
            column: setting_name
            generator:
                strategy: IDENTITY
    fields:
        settingValue:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: setting_value
    lifecycleCallbacks: {  }
