GdUserAccounts:
    type: entity
    table: gd_user_accounts
    id:
        accountId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: account_id
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            comment: ''
            column: date_created
        lastUpdated:
            type: datetime
            nullable: false
            comment: ''
            column: last_updated
        lastLoggedIn:
            type: datetime
            nullable: true
            comment: ''
            column: last_logged_in
        dateExpires:
            type: datetime
            nullable: true
            comment: ''
            column: date_expires
        accountType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: account_type
        firstName:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: last_name
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        passwordRecoveryQuestion:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: password_recovery_question
        passwordRecoveryAnswer:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: password_recovery_answer
        numRowsGenerated:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: num_rows_generated
        maxRecords:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: max_records
    lifecycleCallbacks: {  }
