Person:
    type: entity
    table: person
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Name
        phone:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: Phone
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Email
        birth:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: Birth
        bank:
            type: string
            nullable: true
            length: 34
            fixed: false
            comment: ''
            column: Bank
    lifecycleCallbacks: {  }
