parameters:
#    orm_main.example.class: ORM\MainBundle\Example

services:
#    orm_main.example:
#        class: %orm_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
