ORM\MainBundle\Entity\GdCountries:
    type: entity
    table: gd_countries
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        country:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        countrySlug:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: country_slug
    lifecycleCallbacks: {  }
