<?php

namespace Proxies\__CG__\ORM\MainBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GdUserAccounts extends \ORM\MainBundle\Entity\GdUserAccounts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'accountId', 'dateCreated', 'lastUpdated', 'lastLoggedIn', 'dateExpires', 'accountType', 'firstName', 'lastName', 'email', 'password', 'passwordRecoveryQuestion', 'passwordRecoveryAnswer', 'numRowsGenerated', 'maxRecords');
        }

        return array('__isInitialized__', 'accountId', 'dateCreated', 'lastUpdated', 'lastLoggedIn', 'dateExpires', 'accountType', 'firstName', 'lastName', 'email', 'password', 'passwordRecoveryQuestion', 'passwordRecoveryAnswer', 'numRowsGenerated', 'maxRecords');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GdUserAccounts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAccountId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAccountId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountId', array());

        return parent::getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdated($lastUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdated', array($lastUpdated));

        return parent::setLastUpdated($lastUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdated', array());

        return parent::getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLoggedIn($lastLoggedIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLoggedIn', array($lastLoggedIn));

        return parent::setLastLoggedIn($lastLoggedIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLoggedIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLoggedIn', array());

        return parent::getLastLoggedIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateExpires($dateExpires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateExpires', array($dateExpires));

        return parent::setDateExpires($dateExpires);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateExpires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateExpires', array());

        return parent::getDateExpires();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccountType($accountType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccountType', array($accountType));

        return parent::setAccountType($accountType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountType', array());

        return parent::getAccountType();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRecoveryQuestion($passwordRecoveryQuestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRecoveryQuestion', array($passwordRecoveryQuestion));

        return parent::setPasswordRecoveryQuestion($passwordRecoveryQuestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRecoveryQuestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRecoveryQuestion', array());

        return parent::getPasswordRecoveryQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRecoveryAnswer($passwordRecoveryAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRecoveryAnswer', array($passwordRecoveryAnswer));

        return parent::setPasswordRecoveryAnswer($passwordRecoveryAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRecoveryAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRecoveryAnswer', array());

        return parent::getPasswordRecoveryAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumRowsGenerated($numRowsGenerated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumRowsGenerated', array($numRowsGenerated));

        return parent::setNumRowsGenerated($numRowsGenerated);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumRowsGenerated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumRowsGenerated', array());

        return parent::getNumRowsGenerated();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxRecords($maxRecords)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxRecords', array($maxRecords));

        return parent::setMaxRecords($maxRecords);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxRecords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxRecords', array());

        return parent::getMaxRecords();
    }

}
